### PR TITLE
fix(ImageIOWorker): Wrap the returned errors in a Promise

### PR DESCRIPTION
**Pull request by thewtex**
This improves how the error is handled downstream and improves the message.

### CODE REVIEW

**Comment by thewtex** [comment]
@agirault the second patch should fix the 'out of memory' errors.

**Comment by agirault** [comment]
magnificent

**Comment by agirault** [comment]
@thewtex That did not trigger a new release?

**Comment by thewtex** [comment]
I will shoot for a new release tomorrow.

**Pull request merged**
