### PR TITLE
Hello world example

### PR DESCRIPTION
**Pull request by thewtex**
@fbudin69500 @jcfr @HastingsGreer @floryst please take a look :book:

### CODE REVIEW

**Comment by thewtex** [comment]
Merging so doc's will be published here:

  http://insightsoftwareconsortium.github.io/itk-js/

Feedback welcome! :microphone: :speaker:

**Comment by HastingsGreer** [comment]
The command 
```	npx itk-js build . ```
fails silently for me. Is there a verbose flag?

**Comment by thewtex** [comment]
@HastingsGreer there is no output at all? What version of node / npm / npx do you have?

**Comment by thewtex** [comment]
@HastingsGreer super -- thanks for testing and the information! We probably have an issue with the Docker installation's ability to mount local volumes... I will follow-up IRL to discuss details and see if we can detect the conditions.

**Pull request merged**
